version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6-node-browsers
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
    working_directory: ~/tech-radar
    steps:
      - type: checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: cd assets && yarn && ./node_modules/.bin/brunch build && cd -
      - run: mix test
